// config.ts
export const config = {
  MerryChristmasConfig: {
    requiredScore: 1000,
    clue: "Find your next clue at the top of stargazer!",
  },
  AstridAndOrionConfig: {
    correctWordle: "STRAY",
    correctPurpleGroup: "SEEN IN \"DONKEY KONG\"",
    correctStrandsTheme: "Roll with it",
    clue: "Nice! Your next clue is in xyz location",
  },
  ParagonConfig: {
    minesweeper: {
      gridSize: 22,
      numberOfBombs: 99,
    },
    clue: "You've conquered the mines! Your next clue is in the xyz location.",
  },
  Game2048Config: {
    targetScore: 2048,
    clue: "Congratulations! Your next clue is hidden in the stargazer's telescope.",
  },
  CrosswordConfig: {
    answer: "MATRIX",
    clue: "Follow the white rabbit to the next location.",
  },
  HangmanConfig: {
    words: [
      "MATRIX",
      "CIPHER",
      "DECODE",
      "BINARY",
      "NEURAL",
      "SYSTEM",
      "VECTOR",
      "PORTAL",
      "BRIDGE",
      "SIGNAL",
      "HACK",
      "CODE",
      "PIXEL",
      "GHOST",
      "VIRUS",
      "LOGIC",
      "CYBER",
      "STREAM",
      "DATA",
      "CLOUD",
      "SYNC",
      "NETWORK",
      "QUANTUM",
      "COMPILE",
      "PROGRAM",
      "ENCRYPT",
      "DIGITAL",
      "CONSOLE",
      "FIREWALL",
      "RUNTIME",
      "COMPUTE",
      "VIRTUAL"
    ],
    maxWrongGuesses: 6,
    requiredWins: 3,
    clue: "The next clue awaits in the electric heights.",
  },
  SudokuConfig: {
    clue: "Well done! Your next clue awaits in the ski patrol station.",
  },
};
